/**
 * @packageDocumentation
 * @module api.functional.config.oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as setup from "./setup";
export * as status from "./status";
export * as test from "./test";
